### ISSUE TITLE
Material from RNA-seq/00a-reproducibility_cmdline.md -> working-with-data

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/training-specific-template#23] opened 2020-06-04 16:54 UTC
A lot of the material in the training-module `RNA-seq/00a-reproducibility_cmdline.md` probably would make more sense to be included in the `working-with-your-data` folder that is new to this template. And having a template script for that would probably be good too.

**Comment by jashapiro** [comment] 2020-06-04 17:03
While I agree that a template script might be a good idea, I would argue that  https://github.com/AlexsLemonade/training-modules/blob/master/RNA-seq/00a-reproducibility_cmdline.md does not belong in this repo. 

A separate training module on reproducibility is still in the long term plans, and I think we would be better off moving things in that direction than adding too much to this repo.

**Comment by cansavvy** [comment] 2020-06-04 17:05
Maybe doing both is good?

**Comment by jaclyn-taroni** [comment] 2020-06-04 17:10
Agree that I would leave `00a` where it is for now and we can have evaluating the structure as a logger term goal (including a template script) as part of more material for reproducibility

**Comment by sjspielman** [comment] 2023-09-18 18:57
Closing since we no longer need this feature.

**Closed by sjspielman** 2023-09-18 18:57 UTC
